#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""Generate the ttnn runtime pin and per-capability extras in ``pyproject.toml``.

Single source of truth: ``src/tt_symbiote/models/_runtime_pins.py``. This script
keeps two managed regions of ``pyproject.toml`` in sync with it so packaging can
never drift from the registry / runtime gate:

1. The single ttnn runtime pin, inside the base ``dependencies`` array:

       # >>> ttnn-runtime (generated) >>>
       "ttnn==X.Y.Z",            # or a comment when RELEASE_TTNN is unset
       # <<< ttnn-runtime <<<

2. The shared per-capability extras + the union ``all`` extra, inside
   ``[project.optional-dependencies]``:

       # >>> ttnn-extras (generated) >>>
       vision = ["torchvision"]
       qwen-vl = ["qwen-vl-utils"]
       all = ["qwen-vl-utils", "torchvision"]
       # <<< ttnn-extras <<<

This is the scalable (100+ model) shape: per-model tt-metal commits are metadata
in ``RUNTIME_PINS`` (NOT pip deps); the install side is one ttnn + shared extras,
exactly like ``transformers``' single torch + ``[vision]``/``[audio]`` extras.

Usage::

    python scripts/sync_ttnn_extras.py          # rewrite pyproject.toml in place
    python scripts/sync_ttnn_extras.py --check   # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PYPROJECT = _REPO_ROOT / "pyproject.toml"
_PINS = _REPO_ROOT / "src" / "tt_symbiote" / "models" / "_runtime_pins.py"

_RT_BEGIN = "  # >>> ttnn-runtime (generated by scripts/sync_ttnn_extras.py) >>>"
_RT_END = "  # <<< ttnn-runtime <<<"
_EX_BEGIN = "# >>> ttnn-extras (generated by scripts/sync_ttnn_extras.py) >>>"
_EX_END = "# <<< ttnn-extras <<<"


def _load_pins():
    spec = importlib.util.spec_from_file_location("_runtime_pins", _PINS)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def _toml_list(packages) -> str:
    return "[" + ", ".join(f'"{p}"' for p in packages) + "]"


def _render_runtime(pins) -> str:
    """The ttnn base-deps block (2-space indented to match the array)."""
    release = (pins.RELEASE_TTNN or "").strip()
    lines = [_RT_BEGIN]
    if release:
        lines.append(f'  "ttnn{release}",')
    else:
        lines.append("  # RELEASE_TTNN unset in _runtime_pins.py: source-build only for now")
        lines.append("  # (build ttnn from tt-metal; see docs/development/ttnn_pinning.md).")
    lines.append(_RT_END)
    return "\n".join(lines)


def _render_extras(pins) -> str:
    """The capability extras + `all` block (column-0 TOML table entries)."""
    lines = [
        _EX_BEGIN,
        "# Shared per-capability extras (à la transformers). Models opt in via",
        "# RUNTIME_PINS[...]['extras']. Per-model tt-metal commits are metadata in",
        "# _runtime_pins.py, NOT pip deps (one ttnn per env). Regenerate with",
        "# `python scripts/sync_ttnn_extras.py`.",
    ]
    for name in sorted(pins.CAPABILITY_EXTRAS):
        lines.append(f"{name} = {_toml_list(sorted(pins.CAPABILITY_EXTRAS[name]))}")
    lines.append(f"all = {_toml_list(pins.all_extra_packages())}")
    lines.append(_EX_END)
    return "\n".join(lines)


def _splice(text: str, begin: str, end: str, block: str, region: str) -> str:
    if begin not in text or end not in text:
        raise SystemExit(
            f"{region} markers not found in {_PYPROJECT}; expected:\n  {begin}\n  {end}\n" "Add them and re-run."
        )
    head, _, rest = text.partition(begin)
    _, _, tail = rest.partition(end)
    return head + block + tail


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if pyproject.toml would change")
    args = ap.parse_args()

    pins = _load_pins()
    current = _PYPROJECT.read_text()
    updated = _splice(current, _RT_BEGIN, _RT_END, _render_runtime(pins), "ttnn-runtime")
    updated = _splice(updated, _EX_BEGIN, _EX_END, _render_extras(pins), "ttnn-extras")

    if updated == current:
        return 0
    if args.check:
        sys.stderr.write(
            "pyproject.toml is out of sync with _runtime_pins.py. Run: python scripts/sync_ttnn_extras.py\n"
        )
        return 1
    _PYPROJECT.write_text(updated)
    sys.stderr.write("Updated pyproject.toml (ttnn-runtime + ttnn-extras blocks).\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
